name: Build

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enable VS Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.13.0

      - name: Install InnoSetup
        run: choco install innosetup

      - name: Add InnoSetup to path
        run: echo "C:\Program Files (x86)\Inno Setup 6\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: ninja all
        working-directory: build

      - name: Create installer
        working-directory: build
        run: ..\tools\build-installer.ps1
        shell: powershell

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: Stickit.exe
          path: build/bin/Stickit.exe

      - name: Upload installer
        uses: actions/upload-artifact@v3
        with:
          name: Stickit.Installer.exe
          path: build/Stickit.Installer.exe

  check-release:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
    outputs:
      IS_TAGGED: ${{ steps.is-rel.outputs.IS_TAGGED }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need the tags
      - name: Check Release
        id: is-rel
        run: |
          set +e;
          git describe --exact-match --match 'v*' &> /dev/null;
          echo "IS_TAGGED=$?" >> "$GITHUB_OUTPUT";
        shell: bash

  draft-release:
    runs-on: ubuntu-latest
    needs: [build, check-release]
    if: ${{ needs.check-release.outputs.IS_TAGGED == '0' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need the tags

      - uses: actions/download-artifact@v4
        with:
          name: Stickit.exe
          path: build/

      - uses: actions/download-artifact@v4
        with:
          name: Stickit.Installer.exe
          path: build/

      - name: Get Tag
        id: get-tag
        run: echo "VALUE=$(git describe --exact-match --match 'v*')" >> "$GITHUB_OUTPUT"
      - name: Create release
        uses: ncipollo/release-action@v1.12.0
        with:
          replacesArtifacts: true
          allowUpdates: true
          artifactErrorsFailBuild: true
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          draft: true
          artifacts: "build/*"
          name: ${{ steps.get-tag.outputs.VALUE }}
          tag: ${{ steps.get-tag.outputs.VALUE }}
